const app=document.getElementById('app');
const users=[{id:'sarah',name:'Sarah',pin:'4821',role:'cashier',outlet:'Sunway Pyramid'},{id:'ali',name:'Ali',pin:'9137',role:'manager',outlet:'Sunway Pyramid'},{id:'nurul',name:'Nurul',pin:'2468',role:'cashier',outlet:'Mid Valley'}];
const owner={email:'owner@watermelonsoda.com',password:'Melon2026!'};
const products=[{id:'16',name:'16 oz',price:5},{id:'24',name:'24 oz',price:7}];
let state={mode:'employee',user:null,cart:{},payment:'cash'};
const money=n=>'RM'+Number(n).toFixed(2), sales=()=>JSON.parse(localStorage.getItem('ws_sales')||'[]'), save=x=>localStorage.setItem('ws_sales',JSON.stringify(x)), day=()=>new Date().toISOString().slice(0,10);
function login(){
 app.innerHTML=`<div class="shell"><div class="login"><div class="card brand"><img src="logo.jpg"><h1>Watermelon Soda POS</h1><p>Multi-outlet prototype</p></div><div class="card form"><div class="tabs"><button id="e" class="tab ${state.mode==='employee'?'active':''}">Employee</button><button id="o" class="tab ${state.mode==='owner'?'active':''}">Owner</button></div><div id="f"></div></div></div></div>`;
 e.onclick=()=>{state.mode='employee';login()};o.onclick=()=>{state.mode='owner';login()};
 if(state.mode==='employee'){f.innerHTML=`<h2 class="title">Employee PIN Login</h2><div class="field"><label>Employee</label><select id="u">${users.map(x=>`<option value="${x.id}">${x.name} — ${x.outlet}</option>`).join('')}</select></div><div class="field"><label>PIN</label><input id="pin" maxlength="4" inputmode="numeric" type="password"></div><button class="btn" id="go">Log in</button><div class="note">Demo: Sarah 4821 · Ali 9137 · Nurul 2468</div>`;go.onclick=()=>{let x=users.find(y=>y.id===u.value);if(x&&pin.value===x.pin){state.user=x;state.cart={};pos()}else alert('Incorrect PIN')}}else{f.innerHTML=`<h2 class="title">Owner Login</h2><div class="field"><label>Email</label><input id="em" value="${owner.email}"></div><div class="field"><label>Password</label><input id="pw" type="password" value="${owner.password}"></div><button class="btn" id="go">Open Dashboard</button><div class="note">Data is stored only in this browser.</div>`;go.onclick=()=>{if(em.value===owner.email&&pw.value===owner.password){state.user={name:'Owner',role:'owner'};dashboard()}else alert('Incorrect login')}}}
function pos(){app.innerHTML=`<div class="shell"><div class="top"><div class="left"><img src="logo.jpg"><div><h2 class="title">Watermelon Soda POS</h2><b>${state.user.outlet}</b></div></div><div>${state.user.name} · ${state.user.role}<br><button id="logout">Log out</button></div></div><div class="grid"><div class="card panel"><h3 class="title">Products</h3><div class="products">${products.map(p=>`<button class="product" data-id="${p.id}"><b>${p.name}</b><span>${money(p.price)}</span></button>`).join('')}</div></div><div class="card panel"><h3 class="title">Current Order</h3><div id="list"></div><div class="total"><span>Total</span><span id="tot"></span></div><div class="pays">${['cash','card','qr'].map(x=>`<button class="pay ${state.payment===x?'active':''}" data-pay="${x}">${x.toUpperCase()}</button>`).join('')}</div><button class="btn" id="complete" style="margin-top:12px">Complete Sale</button></div></div></div>`;document.querySelectorAll('.product').forEach(b=>b.onclick=()=>{state.cart[b.dataset.id]=(state.cart[b.dataset.id]||0)+1;cart()});document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>{state.payment=b.dataset.pay;pos()});complete.onclick=finish;logout.onclick=login;cart()}
function cart(){let ids=Object.keys(state.cart).filter(x=>state.cart[x]>0);list.innerHTML=ids.length?ids.map(id=>{let p=products.find(x=>x.id===id),q=state.cart[id];return `<div class="row"><div><b>${p.name}</b><br>${money(p.price)}</div><div class="qty"><button data-m="${id}">−</button> ${q} <button data-p="${id}">+</button></div><b>${money(p.price*q)}</b></div>`}).join(''):'<div class="note">Tap a product to begin.</div>';document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{state.cart[b.dataset.m]--;cart()});document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.cart[b.dataset.p]++;cart()});tot.textContent=money(total())}
function total(){return Object.entries(state.cart).reduce((a,[id,q])=>a+products.find(p=>p.id===id).price*q,0)}
function finish(){if(!total())return alert('Add an item');let x=sales();x.push({date:new Date().toISOString(),day:day(),outlet:state.user.outlet,employee:state.user.name,payment:state.payment,total:total(),items:state.cart});save(x);state.cart={};alert('Sale saved');cart()}
function dashboard(){let t=sales().filter(x=>x.day===day()),sum=t.reduce((a,x)=>a+x.total,0),cups=t.reduce((a,x)=>a+Object.values(x.items).reduce((b,q)=>b+q,0),0),outs=[...new Set(users.map(x=>x.outlet))];app.innerHTML=`<div class="shell"><div class="top"><div class="left"><img src="logo.jpg"><h2 class="title">Watermelon Soda HQ</h2></div><button id="logout">Log out</button></div><div class="metrics">${[['Today sales',money(sum)],['Cups sold',cups],['Transactions',t.length],['Active outlets',outs.length]].map(x=>`<div class="card metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="owner"><div class="card panel"><h3 class="title">Sales by outlet</h3><table>${outs.map(o=>`<tr><td>${o}</td><td>${money(t.filter(x=>x.outlet===o).reduce((a,x)=>a+x.total,0))}</td></tr>`).join('')}</table></div><div class="card panel"><h3 class="title">Recent activity</h3><table>${t.slice(-8).reverse().map(x=>`<tr><td>${x.employee}</td><td>${x.outlet}</td><td>${money(x.total)}</td></tr>`).join('')||'<tr><td>No sales yet</td></tr>'}</table></div></div><div class="note">Prototype limitation: no cloud sync yet. Production use needs a secure backend and hosted database.</div></div>`;logout.onclick=login}
login();